### ISSUE TITLE
ERROR: Python provider error 

### ISSUE THREAD

**Issue by SS90ss** [glepnir/jarvim#11]
ERROR: Python provider error 
不知道怎么回事好像Python3没工作？但是我安装了Python啊
![截图_2020-08-31_22-51-03](https://user-images.githubusercontent.com/56617556/91734216-3a802d80-ebdd-11ea-96f4-9fd077f8434d.png)
![截图_2020-08-31_22-53-20](https://user-images.githubusercontent.com/56617556/91734238-45d35900-ebdd-11ea-925b-2db7e02cecb9.png)
[aa.log](https://github.com/glepnir/jarvim/files/5151006/aa.log)

**Comment by glepnir** [comment]
执行下`checkhealth` 查看python3 host
