### ISSUE TITLE
<leader> F 报错

### ISSUE THREAD

**Issue by cuiko** [glepnir/jarvim#16]
\<leader\> e 命令正常,
\<leader\> F 命令有报错

我是一个 vim 新手, 用 jarvim -g 跑完后, 现在在对着 pmap.vim 和 vmap.vim 文件试命令, 试着试着试到有个报错了, 大佬们有空帮我看看啥问题吗?

![QQ截图20201214110022](https://user-images.githubusercontent.com/33982919/102035908-970a0000-3dfc-11eb-9ebd-12142b55b348.png)

**Comment by glepnir** [comment]
换成这个试试
```vim
nnoremap <silent> <Leader>F
		\ :<C-u>Defx
		\   -search=`escape(expand('%:p'), ' :')`
		\   -buffer-name=explorer`tabpagenr()`<CR>
```

**Comment by cuiko** [comment]
抱歉, 回复晚了

谢谢大佬指点, 现在没有报错了

![QQ截图20201214124317](https://user-images.githubusercontent.com/33982919/102041333-28cc3a00-3e0a-11eb-82fb-2c5101cf361a.png)

**Comment by zhangweiii** [comment]
> 换成这个试试
> 
> ```viml
> nnoremap <silent> <Leader>F
> 		\ :<C-u>Defx
> 		\   -search=`escape(expand('%:p'), ' :')`
> 		\   -buffer-name=explorer`tabpagenr()`<CR>
> ```

但是会出现一个新问题，就是我打开vim，然后<Leader>E打开目录树，然后目录树中打开一个文件，然后<Leader>F，此时会出现两个目录树
