### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by krisfans** [glepnir/jarvim#22]
使用`jarvim`生成配置，忽略了这四项，`Datbase`，`editorconfig`，`vim-quickrun`，`quickrun`后执行`sh ./install.sh`报错`./install.sh: 14: Syntax error: "(" unexpected`
![Snipaste_2021-03-24_11-57-49](https://user-images.githubusercontent.com/57793534/112252736-95bc5f00-8c98-11eb-9118-6b39473005ef.png)
生成的`install.sh`如下
[install.sh](https://github.com/glepnir/jarvim/files/6194283/install.log)

**Comment by krisfans** [comment]
运行环境是windows10 + wsl2+ubuntu20.04+NVIM v0.5.0-dev+1165-ge5bef5974

**Comment by glepnir** [comment]
选dein

**Comment by krisfans** [comment]
插件管理器选的是`dein`，问题是用sh install.sh不行(B站演示的时候可以)，必须用`bash `
另外，默认的buffline插件不能用[https://github.com/hardcoreplayers/vim-buffet](url)
