### ISSUE TITLE
E121: Undefined variable: execute

### ISSUE THREAD

**Issue by HappyMan01** [glepnir/jarvim#6]
安装完成后终端输入nvim 并没有出现预期的效果，而是nervim的欢迎页，上面的报错的位置是在我的init.vim文件，他说没有定义这个变量,我的init.vim里面的内容是：
execute 'source' fnamemodify(expand('<sfile>'), ':h').'/core/core.vim'execute 'source' fnamemodify(expand('<sfile>'), ':h').'/core/core.vim'

**Comment by glepnir** [comment]
@HappyMan01 。。你这不是重复了吗。

**Comment by glepnir** [comment]
```vim
execute 'source' fnamemodify(expand('<sfile>'), ':h').'/core/core.vim'
```

**Comment by HappyMan01** [comment]
好的 谢谢
