### ISSUE TITLE
An error occurred while executing make

### ISSUE THREAD

**Issue by xxxxzb** [glepnir/jarvim#9]
I use archlinux (kernel 5.8.4). nvim version 0.4.4.
An error occurred while executing `make`.

> $ make
could not source "--noplugin"
E282: Cannot read from "--noplugin"
not found in 'runtimepath': "ftdetect/*.vim"
not found in 'packpath': "pack/*/start/*"
not found in 'packpath': "pack/*/start/matchit"
not found in 'packpath': "pack/*/start/*"
not found in 'runtimepath': "plugin/**/*.vim"
not found in 'runtimepath': "autoload/dein.vim"
not found in 'runtimepath': "autoload/dein.vim"
Error detected while processing command line:
E117: Unknown function: dein#update
Entering Ex mode.  Type "visual" to go to Normal mode.
:make: *** [Makefile:10: install] Error 1

I found that it is Line 11 Col 34 of Makefile, vim has one more parameter.
```makefile
~/.config/nvim/Makefile
...
 $(vim)  -V1 -es -i NONE -N -u --noplugin core/dein.vim -c ...
...
```
When I deleted --noplugin. `make` again. There is another error.
> $ make
[dein] Invalid toml format: /home/xzb/.config/nvim/modules/languages.toml
[dein] Text.TOML: Illegal toml format at L7:`[[plugins]]':64.
not found in 'packpath': "pack/*/start/*"
not found in 'packpath': "pack/*/start/matchit"
not found in 'packpath': "pack/*/start/*"
[dein] Update started: (2020/08/29 09:38:08)
[dein] (12/54) [++++----------------] spaceline.vim
[dein] (13/54) [++++----------------] vim-buffet
[dein] (15/54) [+++++---------------] vim-sandwich
[dein] (22/54) [++++++++------------] coc-clap
[dein] (23/54) [++++++++------------] vim-toml
[dein] (24/54) [++++++++------------] vim-solarized8
[dein] (25/54) [+++++++++-----------] vim-quickrun
[dein] (26/54) [+++++++++-----------] committia.vim
[dein] (32/54) [+++++++++++---------] context_filetype.vim
[dein] (37/54) [+++++++++++++-------] coc.nvim
[dein] (38/54) [++++++++++++++------] nord-vim
[dein] (40/54) [++++++++++++++------] vim-markdown
[dein] (42/54) [+++++++++++++++-----] dashboard-nvim
[dein] (44/54) [++++++++++++++++----] jellybeans.vim
[dein] (46/54) [+++++++++++++++++---] vim-textobj-multiblock
[dein] (47/54) [+++++++++++++++++---] base16-vim
[dein] (48/54) [+++++++++++++++++---] vim-hybrid-material
[dein] (49/54) [++++++++++++++++++--] markdown-preview.nvim
[dein] (50/54) [++++++++++++++++++--] vim-floaterm
[dein] (51/54) [++++++++++++++++++--] vim-devicons
[dein] (52/54) [+++++++++++++++++++-] splitjoin.vim
[dein] Done: (2020/08/29 09:38:20)/bin/bash: line 1: @rm: command not found
/bin/bash: line 2: @rm: command not found

I have no idea how to modify it to execute successfully.Please tell me what to do.

**Comment by glepnir** [comment]
@xxxxzb what about this
```makefile
$(vim)  -V1 -es -i NONE -N --noplugin -u core/dein.vim -c "try | call dein#update() | call dein#recache_runtimepath() | finally | echomsg '' | qall! | endtry"

**Comment by xxxxzb** [comment]
@glepnir Great, it work. 
Although there is an error message, it can still be installed successfully.
> $ make
[dein] Invalid toml format: /home/xzb/.config/nvim/modules/languages.toml
[dein] Text.TOML: Illegal toml format at L7:`[[plugins]]':64.
[dein] Update started: (2020/08/29 16:11:52)
[dein] (12/55) [++++----------------] spaceline.vim
[dein] (20/55) [+++++++-------------] vim-one
[dein] (24/55) [++++++++------------] vim-solarized8
[dein] (25/55) [+++++++++-----------] vim-quickrun
[dein] (29/55) [++++++++++----------] vim-expand-region
[dein] (32/55) [+++++++++++---------] context_filetype.vim
[dein] (35/55) [++++++++++++--------] oceanic-next
[dein] (36/55) [+++++++++++++-------] vim-textobj-function
[dein] (37/55) [+++++++++++++-------] coc.nvim
[dein] (39/55) [++++++++++++++------] nord-vim
[dein] (42/55) [+++++++++++++++-----] vim-jsonc
[dein] (45/55) [++++++++++++++++----] jellybeans.vim
[dein] (48/55) [+++++++++++++++++---] base16-vim
[dein] (49/55) [+++++++++++++++++---] vim-hybrid-material
[dein] (50/55) [++++++++++++++++++--] markdown-preview.nvim
[dein] (52/55) [++++++++++++++++++--] vim-devicons
[dein] Done: (2020/08/29 16:12:02)/bin/bash: line 1: @rm: command not found
/bin/bash: line 2: @rm: command not found

Can you guide me to solve this problem. I did not recognize what is wrong with languages.toml.
> [dein] Invalid toml format: /home/xzb/.config/nvim/modules/languages.toml
[dein] Text.TOML: Illegal toml format at L7:`[[plugins]]':64.

```bash
~/.config/nvim/modules/languages.toml
───┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │
   2   │ [[plugins]]
   3   │ repo = 'hail2u/vim-css3-syntax'
   4   │ on_ft = 'css'
   5   │ '''
   6   │
   7   │ [[plugins]]
   8   │ repo = 'pangloss/vim-javascript'
   9   │ on_ft = [ 'javascript', 'javascriptreact' ]
  10   │ hook_source = '''
  11   │     let g:javascript_plugin_jsdoc = 1
  12   │     let g:javascript_plugin_flow = 1
  13   │ '''
```

**Comment by glepnir** [comment]
It is right.

**Comment by StrayDragon** [comment]
Same issue, maybe need a hotfix patch 😂

**Comment by xxxxzb** [comment]
> It is right.
thank you ~

**Comment by xxxxzb** [comment]
> Same issue, maybe need a hotfix patch joy

It’s normal for a new project to have problems, but this is the most helpful project I have seen about vim ╮(￣▽￣)╭

**Comment by glepnir** [comment]
I had fix on upstream.
